version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /searchresult
  script: Search.app
  login: required

- url: /search
  script: Search.app
  login: required

- url: /showmore.*
  script: ViewSingle.app
  login: required

- url: /pic.*
  script: ViewSingle.app
  login: required

- url: /upload
  script: ViewSingle.app
  login: required

- url: /stream.*
  script: ViewSingle.app
  login: required

- url: /sign
  script: Create.app
  login: required

- url: /error
  script: Error.app
  #login: required

- url: /management
  script: Management.app
  login: required

- url: /deletestream
  script: Management.app
  login: required

- url: /create
  script: Create.app
  login: required

- url: /view
  script: View.app
  login: required

- url: /search
  script: Search.app
  login: required

- url: /trending
  script: Trending.app
  login: required

- url: /social
  script: Social.app
  login: required

- url: /.*
  script: Login.app
  #login: required

libraries:
- name: webapp2
  version: latest

- name: PIL
  version: latest