version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /error
  script: Error.app
  login: required

- url: /management
  script: Management.app
  login: required

- url: /create
  script: Create.app
  login: required

- url: /view
  script: View.app
  login: required

- url: /search
  script: Search.app
  login: required

- url: /trending
  script: Trending.app
  login: required

- url: /social
  script: Social.app
  login: required

- url: /.*
  script: Login.app
  #slogin: required

libraries:
- name: webapp2
  version: latest